<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "    <head>\n";
print "	<meta charset=\"utf-8\" />\n";
print "	<title>Ping for Twitch</title>\n";
print "    </head>\n";
print "    <body>\n";
print "	<button id=\"ping\">HTTP Ping</button>\n";
print "	<table>\n";
print "	    <thead>\n";
print "		<tr><td>Address</td><td>Server</td><td>Ping</td></tr>\n";
print "	    </thead>\n";
print "	    <tbody>\n";
print "		<tr><td>live-hkg.twitch.tv</td><td>AS: Hong Kong</td><td></td></tr>\n";
print "		<tr><td>live-sel.twitch.tv</td><td>AS: Seoul, South Korea</td><td></td></tr>\n";
print "		<tr><td>live-sin.twitch.tv</td><td>AS: Singapore</td><td></td></tr>\n";
print "		<tr><td>live-tpe.twitch.tv</td><td>AS: Taipei, Taiwan</td><td></td></tr>\n";
print "		<tr><td>live-tyo.twitch.tv</td><td>AS: Tokyo, Japan</td><td></td></tr>\n";
print "		<tr><td>live-syd.twitch.tv</td><td>AU: Sydney</td><td></td></tr>\n";
print "		<tr><td>live-ams.twitch.tv</td><td>EU: Amsterdam, NL</td><td></td></tr>\n";
print "		<tr><td>live-fra.twitch.tv</td><td>EU: Frankfurt, Germany</td><td></td></tr>\n";
print "		<tr><td>live-lhr.twitch.tv</td><td>EU: London, UK</td><td></td></tr>\n";
print "		<tr><td>live-cdg.twitch.tv</td><td>EU: Paris, FR</td><td></td></tr>\n";
print "		<tr><td>live-prg.twitch.tv</td><td>EU: Prague, CZ</td><td></td></tr>\n";
print "		<tr><td>live-arn.twitch.tv</td><td>EU: Stockholm, Sweden</td><td></td></tr>\n";
print "		<tr><td>live-waw.twitch.tv</td><td>EU: Warsaw, Poland</td><td></td></tr>\n";
print "		<tr><td>live-eze.twitch.tv</td><td>South America: Argentina</td><td></td></tr>\n";
print "		<tr><td>live-scl.twitch.tv</td><td>South America: Chile</td><td></td></tr>\n";
print "		<tr><td>live-gig.twitch.tv</td><td>South America: Rio de Janeiro, Brazil</td><td></td></tr>\n";
print "		<tr><td>live-gru.twitch.tv</td><td>South America: Sao Paulo, Brazil</td><td></td></tr>\n";
print "		<tr><td>live-dfw.twitch.tv</td><td>US Central: Dallas, TX</td><td></td></tr>\n";
print "		<tr><td>live-iad.twitch.tv</td><td>US East: Ashburn, VA</td><td></td></tr>\n";
print "		<tr><td>live-ord.twitch.tv</td><td>US East: Chicago</td><td></td></tr>\n";
print "		<tr><td>live-mia.twitch.tv</td><td>US East: Miami, FL</td><td></td></tr>\n";
print "		<tr><td>live-jfk.twitch.tv</td><td>US East: New York, NY</td><td></td></tr>\n";
print "		<tr><td>live-lax.twitch.tv</td><td>US West: Los Angeles, CA</td><td></td></tr>\n";
print "		<tr><td>live.twitch.tv</td><td>US West: San Francisco, CA</td><td></td></tr>\n";
print "		<tr><td>live-sjc.twitch.tv</td><td>US West: San Jose,CA</td><td></td></tr>\n";
print "		<tr><td>live-sea.twitch.tv</td><td>US West: Seattle,WA</td><td></td></tr>\n";
print "	    </tbody>\n";
print "	</table>\n";
print "	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\n";
print "	<script src=\"https://cdn.rawgit.com/jdfreder/pingjs/c2190a3649759f2bd8569a72ae2b597b2546c871/ping.js\"></script>\n";
print "	<script src=\"https://cdn.jsdelivr.net/tablesorter/2.17.4/js/jquery.tablesorter.min.js\"></script>\n";
print "	<script>\n";
print "			function cb(self, delta) {\n";
print "				$(self).find('td:last-child').text(delta + ' ms');\n";
print "				if ($(self).find('td:first-child').text() === $('tbody tr:last-child td:first-child').text()) {\n";
print "					$('table').tablesorter();\n";
print "				} else {\n";
print "					ping('http://' + $(self).next().find('td:first-child').text() + ':1935').then(function (delta) {\n";
print "						cb($(self).next(), delta);\n";
print "					});\n";
print "				}\n";
print "			}\n";
print "			$('#ping').click(function () {\n";
print "				var self = $('tbody tr:first-child');\n";
print "				ping('http://' + $(self).find('td:first-child').text() + ':1935').then(function (delta) {\n";
print "					cb(self, delta);\n";
print "				});\n";
print "			});\n";
print "	</script>\n";
print "    </body>\n";
print "</html>\n";

?>
