<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\" />\n";
echo "    <title>Ping All Twitch Servers</title>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "    <button id=\"ping\">HTTP Ping</button>\n";
echo "    <table>\n";
echo "        <thead>\n";
echo "            <tr>\n";
echo "                <td>Address</td>\n";
echo "                <td>Server</td>\n";
echo "                <td>Ping</td>\n";
echo "            </tr>\n";
echo "        </thead>\n";
echo "        <tbody>\n";
echo "            <tr>\n";
echo "                <td>live-hkg.twitch.tv</td>\n";
echo "                <td>AS: Hong Kong</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-sel.twitch.tv</td>\n";
echo "                <td>AS: Seoul, South Korea</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-sin.twitch.tv</td>\n";
echo "                <td>AS: Singapore</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-tpe.twitch.tv</td>\n";
echo "                <td>AS: Taipei, Taiwan</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-tyo.twitch.tv</td>\n";
echo "                <td>AS: Tokyo, Japan</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-syd.twitch.tv</td>\n";
echo "                <td>AU: Sydney</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-ams.twitch.tv</td>\n";
echo "                <td>EU: Amsterdam, NL</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-fra.twitch.tv</td>\n";
echo "                <td>EU: Frankfurt, Germany</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-lhr.twitch.tv</td>\n";
echo "                <td>EU: London, UK</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-cdg.twitch.tv</td>\n";
echo "                <td>EU: Paris, FR</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-prg.twitch.tv</td>\n";
echo "                <td>EU: Prague, CZ</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-arn.twitch.tv</td>\n";
echo "                <td>EU: Stockholm, Sweden</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-waw.twitch.tv</td>\n";
echo "                <td>EU: Warsaw, Poland</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-eze.twitch.tv</td>\n";
echo "                <td>South America: Argentina</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-scl.twitch.tv</td>\n";
echo "                <td>South America: Chile</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-gig.twitch.tv</td>\n";
echo "                <td>South America: Rio de Janeiro, Brazil</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-gru.twitch.tv</td>\n";
echo "                <td>South America: Sao Paulo, Brazil</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-dfw.twitch.tv</td>\n";
echo "                <td>US Central: Dallas, TX</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-iad.twitch.tv</td>\n";
echo "                <td>US East: Ashburn, VA</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-ord.twitch.tv</td>\n";
echo "                <td>US East: Chicago</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-mia.twitch.tv</td>\n";
echo "                <td>US East: Miami, FL</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-jfk.twitch.tv</td>\n";
echo "                <td>US East: New York, NY</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-lax.twitch.tv</td>\n";
echo "                <td>US West: Los Angeles, CA</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live.twitch.tv</td>\n";
echo "                <td>US West: San Francisco, CA</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-sjc.twitch.tv</td>\n";
echo "                <td>US West: San Jose,CA</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>live-sea.twitch.tv</td>\n";
echo "                <td>US West: Seattle,WA</td>\n";
echo "                <td></td>\n";
echo "            </tr>\n";
echo "        </tbody>\n";
echo "    </table>\n";
echo "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\n";
echo "    <script src=\"https://cdn.rawgit.com/jdfreder/pingjs/c2190a3649759f2bd8569a72ae2b597b2546c871/ping.js\"></script>\n";
echo "    <script src=\"https://cdn.jsdelivr.net/tablesorter/2.17.4/js/jquery.tablesorter.min.js\"></script>\n";
echo "    <script>\n";
echo "        function cb(self, delta) {\n";
echo "            $(self).find('td:last-child').text(delta + ' ms');\n";
echo "            if ($(self).find('td:first-child').text() === $('tbody tr:last-child td:first-child').text()) {\n";
echo "                $('table').tablesorter();\n";
echo "            } else {\n";
echo "                ping('http://' + $(self).next().find('td:first-child').text() + ':1935').then(function(delta) {\n";
echo "                    cb($(self).next(), delta);\n";
echo "                });\n";
echo "            }\n";
echo "        }\n";
echo "        $('#ping').click(function() {\n";
echo "            var self = $('tbody tr:first-child');\n";
echo "            ping('http://' + $(self).find('td:first-child').text() + ':1935').then(function(delta) {\n";
echo "                cb(self, delta);\n";
echo "            });\n";
echo "        });\n";
echo "    </script>\n";
echo "</body>\n";
echo "\n";
echo "</html>";

?>
